title: Kinect Menü
source: doc_src
destination: doc

baseurl: ""

compress_html:
  blanklines: true

collections:
  implementation:
    output: true
    submenu: true
    menupos: 4
    title: "Implementierung"
